export const GAME_CONSTANTS = {
  CONTAINER_SIZE: 600,
  POINT_SIZE: 50,
  MIN_POINTS: 5,
  MAX_POINTS: 2000,
  TIMER_INTERVAL: 100,
  TIMER_INCREMENT: 0.1,
  // Animation constants
  POINT_COUNTDOWN: 3,
  FADE_OUT_DURATION: 0.5,
  COUNTDOWN_INTERVAL: 100,
  COUNTDOWN_DECREMENT: 0.1,
  // Z-index values
  POINT_Z_INDEX: 1,
  CLICKED_POINT_Z_INDEX: 10
} as const;
